2018-11-15T16:08:23|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\logged_quantity.py", line 241, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\Admin\Desktop\Camera-ScopeFoundry\CameraDevice.py", line 697, in setSubarrayH
    self.setPropertyValue("subarray_hsize", hsize)
  File "C:\Users\Admin\Desktop\Camera-ScopeFoundry\CameraDevice.py", line 751, in setPropertyValue
    raise DCAMException(" The parameter is not valid, the set value is: {}".format(actual_val))
CameraDevice.DCAMException:  The parameter is not valid, the set value is: 2048

