2018-11-08T17:18:20|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: cannot reshape array of size 2097152 into shape (2048,2048). ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 54, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py", line 279, in reshape\n    return _wrapfunc(a, \'reshape\', newshape, order=order)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py", line 51, in _wrapfunc\n    return getattr(obj, method)(*args, **kwds)\n', 'ValueError: cannot reshape array of size 2097152 into shape (2048,2048)\n']
2018-11-08T17:18:20|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: cannot reshape array of size 2097152 into shape (2048,2048). ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 54, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py", line 279, in reshape\n    return _wrapfunc(a, \'reshape\', newshape, order=order)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py", line 51, in _wrapfunc\n    return getattr(obj, method)(*args, **kwds)\n', 'ValueError: cannot reshape array of size 2097152 into shape (2048,2048)\n']
2018-11-08T17:18:20|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: cannot reshape array of size 2097152 into shape (2048,2048). ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 54, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py", line 279, in reshape\n    return _wrapfunc(a, \'reshape\', newshape, order=order)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py", line 51, in _wrapfunc\n    return getattr(obj, method)(*args, **kwds)\n', 'ValueError: cannot reshape array of size 2097152 into shape (2048,2048)\n']
2018-11-08T17:18:20|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: cannot reshape array of size 2097152 into shape (2048,2048). ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 54, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py", line 279, in reshape\n    return _wrapfunc(a, \'reshape\', newshape, order=order)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py", line 51, in _wrapfunc\n    return getattr(obj, method)(*args, **kwds)\n', 'ValueError: cannot reshape array of size 2097152 into shape (2048,2048)\n']
