2018-11-09T11:07:09|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 179, in _thread_run
    self.run()
  File "C:\Users\Admin\Desktop\Camera-ScopeFoundry\CameraMeasurement.py", line 81, in run
    self.camera.hamamatsu.stopAcquisition()
  File "C:\Users\Admin\Desktop\Camera-ScopeFoundry\CameraDevice.py", line 797, in stopAcquisition
    DCAMBUF_ATTACHKIND_FRAME),
OSError: exception: access violation reading 0x000002690D89403F

