2018-11-15T15:17:26|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Camera-ScopeFoundry\CameraMeasurement.py", line 81, in run
    self.camera.hamamatsu.startAcquisition()
AttributeError: 'HamamatsuHardware' object has no attribute 'hamamatsu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 179, in _thread_run
    self.run()
  File "C:\Users\Admin\Desktop\Camera-ScopeFoundry\CameraMeasurement.py", line 117, in run
    self.camera.hamamatsu.stopAcquisition()
AttributeError: 'HamamatsuHardware' object has no attribute 'hamamatsu'

2018-11-15T15:17:38|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Camera-ScopeFoundry\CameraMeasurement.py", line 102, in run
    [frames, dims] = self.camera.hamamatsu.getFrames()
AttributeError: 'HamamatsuHardware' object has no attribute 'hamamatsu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 179, in _thread_run
    self.run()
  File "C:\Users\Admin\Desktop\Camera-ScopeFoundry\CameraMeasurement.py", line 117, in run
    self.camera.hamamatsu.stopAcquisition()
AttributeError: 'HamamatsuHardware' object has no attribute 'hamamatsu'

