2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:03|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:04|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:05|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
2018-11-30T17:42:06|ERROR|HamamatsuMeasurement|hamamatsu_image Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'autoscale'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\Camera-ScopeFoundry\\CameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.image).T, autoLevels=self.autoLevels, autoRange=self.autoscale)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'autoscale'\n"]
