2018-11-30T11:55:35|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 179, in _thread_run
    self.run()
  File "C:\LabPrograms\Python\Camera-ScopeFoundry\CameraMeasurement.py", line 140, in run
    self.camera.hamamatsu.startRecording( HamamatsuApp.settings.save_dir)
NameError: name 'HamamatsuApp' is not defined

