2018-11-08T17:36:12|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:12|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:13|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:13|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:13|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:13|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:13|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:13|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:13|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:13|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:13|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:14|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:14|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:14|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:14|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:14|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:14|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:36:14|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(self.camera.subarrayh.val, self.camera.subarrayv.val)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
