2018-11-08T16:04:24|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:24|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:24|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:24|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:24|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:24|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:24|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:24|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:24|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:25|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:25|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:25|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:25|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:25|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:25|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:25|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:25|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T16:04:25|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 52, in update_display\n    self.imv.setImage(np.reshape(self.np_data,(2048, 2048)).T)\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
