2018-11-08T17:59:40|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Camera-ScopeFoundry\CameraApp.py", line 24, in <module>
    app = HamamatsuApp(sys.argv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 334, in __init__
    self.setup_default_ui()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 365, in setup_default_ui
    measure.setup_figure()
  File "C:\Users\Admin\Desktop\Camera-ScopeFoundry\CameraMeasurement.py", line 43, in setup_figure
    sel.imv.show()
NameError: name 'sel' is not defined

