2018-11-08T17:38:39|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    if len(self.np_data.val)!=0 :\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:38:39|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    if len(self.np_data.val)!=0 :\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:38:39|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    if len(self.np_data.val)!=0 :\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:38:39|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    if len(self.np_data.val)!=0 :\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:38:39|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    if len(self.np_data.val)!=0 :\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:38:39|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    if len(self.np_data.val)!=0 :\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:38:40|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    if len(self.np_data.val)!=0 :\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:38:40|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    if len(self.np_data.val)!=0 :\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:38:40|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'HamamatsuMeasurement' object has no attribute 'np_data'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    if len(self.np_data.val)!=0 :\n', "AttributeError: 'HamamatsuMeasurement' object has no attribute 'np_data'\n"]
2018-11-08T17:38:40|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'numpy.ndarray' object has no attribute 'val'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    if len(self.np_data.val)!=0 :\n', "AttributeError: 'numpy.ndarray' object has no attribute 'val'\n"]
2018-11-08T17:38:40|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'numpy.ndarray' object has no attribute 'val'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    if len(self.np_data.val)!=0 :\n', "AttributeError: 'numpy.ndarray' object has no attribute 'val'\n"]
2018-11-08T17:38:40|ERROR|HamamatsuMeasurement|hamamatsu_plot Failed to update figure1: 'numpy.ndarray' object has no attribute 'val'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Admin\\Desktop\\Camera-ScopeFoundry\\CameraMeasurement.py", line 56, in update_display\n    if len(self.np_data.val)!=0 :\n', "AttributeError: 'numpy.ndarray' object has no attribute 'val'\n"]
